networks:
  key-network:
    driver: bridge

services:
  postgres-db:
    container_name: my_postgres
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres:/var/lib/postgres/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - key-network

  pg-admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - key-network

  backend:
    build:
      dockerfile: Dockerfile
    container_name: fullstack
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    networks:
      - key-network