networks:
  key-network:
    driver: bridge

services:
  postgres-db:
    image: postgres:17.2-alpine3.21
    container_name: my_postgres
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres:/var/lib/postgres/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - key-network

#  http://localhost:8100/login?next=/browser/
#  PGADMIN+TESTCONTAINERS

  backend:
    build:
      dockerfile: Dockerfile
    container_name: fullstack
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
    depends_on:
      - postgres-db
    ports:
      - "8001:8080"
    networks:
      - key-network


#      - networks:
#          key-network:
#            driver: bridge
#        services:
#          key-postgresql:
#            image: postgres:14.5
#            container_name: postgres-db
#            volumes:
#              - ~/key-app/volumes/postgresql/:/var/lib/postgresql/data/
#              - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#            environment:
#              - POSTGRES_USER=postgres
#              - POSTGRES_PASSWORD=root
#              - POSTGRES_HOST_AUTH_METHOD=trust
#              - POSTGRES_DB=key_db
#              - TZ=Asia/Almaty
#            ports:
#              - '5432:5432'
#            networks:
#              - key-network
#            healthcheck:
#              test: [ "CMD", "pg_isready", "-U", "webcom", "-d", "key_db" ]
#              interval: 10s
#              retries: 5
#              start_period: 10s
#
#          key-pg_admin:
#            image: dpage/pgadmin4
#            container_name: pg-admin
#            environment:
#              PGADMIN_DEFAULT_EMAIL: user
#              PGADMIN_DEFAULT_PASSWORD: pass
#            ports:
#              - '8700:80'
#            depends_on:
#              - key-postgresql
#            networks:
#              - key-network
#
#          key-app:
#            image: key-backend
#            container_name: key-app
#            build:
#              context: .
#              dockerfile: Dockerfile
#            environment:
#              - _JAVA_OPTIONS=-Xmx4g -Xms2g
#              - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
#              - SPRING_DATASOURCE_URL=jdbc:postgresql://key-postgresql:5432/postgres
#            user: '${UID}:${GID}'
#            ports:
#              - '1360:1360'
#            depends_on:
#              key-postgresql:
#                condition: service_healthy
#            networks:
#              - key-network